### ISSUE TITLE
Parsowanie JSON

### ISSUE THREAD

**Issue by PiotrJTomaszewski** [PiotrJTomaszewski/IO-Buildings#5]
Przetwarzanie danych usyskanych od klienta w formacie JSON, jak również pakowanie odpowiedzi dla klienta do JSON. 
Oszacowana pracochłonność; 0.5

**Comment by Ztrk** [comment]
Parsowanie JSONów jest robione przez Springa (konkretnie przez bibliotekę Jackson). Wystarczyło jedynie dodać odpowiednie adnotacje, aby Jackson rozumiał hierarchię klas.
