### ISSUE TITLE
Implementacja struktury danych

### ISSUE THREAD

**Issue by PiotrJTomaszewski** [PiotrJTomaszewski/IO-Buildings#6]
Stworzenie struktury danych, w której będziemy przechowywać otrzymane informacje.
Oszacowana pracochłonność: 1

**Comment by PiotrJTomaszewski** [comment]
Trzeba się zorientować czy mamy implementować bazę danych, czy dane będziemy otrzymywać przy każdym zapytaniu.

**Comment by Ztrk** [comment]
Nie potrzebujemy żadnych zewnętrznych struktur, wystarczy nam tylko hierarchia klas oraz mapowanie klas na JSON - to jest już skończone.
